GET http://localhost:3004/
###

GET http://localhost:3004/sighting
###

POST http://localhost:3004/sighting
Content-Type: application/x-www-form-urlencoded

city=City value
&state=TestState value
&shape=Shape value
&text=Text value
&summary=Summary value
###

PUT http://localhost:3004/sighting/2
Content-Type: application/x-www-form-urlencoded

text=Text values
&city=City value test
&state=TestState value test
&shape=Shape value test
&summary=Summary value test
###

DELETE http://localhost:3004/sighting/3
###

GET http://localhost:3004/sighting/1
###

GET http://localhost:3004/sighting/1/edit
###

GET http://localhost:3004/shapes
###

GET http://localhost:3004/shapes/fireball
###

GET http://localhost:3004/shapes/sphere
###

